In [1]:
pip list

Package                       Version
----------------------------- ----------------------
absl-py                       1.3.0
aeppl                         0.0.33
aesara                        2.7.9
aiohttp                       3.8.3
aiosignal                     1.3.1
alabaster                     0.7.12
albumentations                1.2.1
altair                        4.2.0
appdirs                       1.4.4
arviz                         0.12.1
astor                         0.8.1
astropy                       4.3.1
astunparse                    1.6.3
async-timeout                 4.0.2
atari-py                      0.2.9
atomicwrites                  1.4.1
attrs                         22.1.0
audioread                     3.0.0
autograd                      1.5
Babel                         2.11.0
backcall                      0.2.0
beautifulsoup4                4.6.3
bleach                        5.0.1
blis                          0.7.9
bokeh                         2.3.3
branca                        0.6.0
bs4                           0.0.1
CacheControl                  0.12.11
cachetools                    5.2.0
catalogue                     2.0.8
certifi                       2022.12.7
cffi                          1.15.1
cftime                        1.6.2
chardet                       3.0.4
charset-normalizer            2.1.1
click                         7.1.2
clikit                        0.6.2
cloudpickle                   1.5.0
cmake                         3.22.6
cmdstanpy                     1.0.8
colorcet                      3.0.1
colorlover                    0.3.0
community                     1.0.0b1
confection                    0.0.3
cons                          0.4.5
contextlib2                   0.5.5
convertdate                   2.4.0
crashtest                     0.3.1
crcmod                        1.7
cufflinks                     0.17.3
cvxopt                        1.3.0
cvxpy                         1.2.2
cycler                        0.11.0
cymem                         2.0.7
Cython                        0.29.32
daft                          0.0.4
dask                          2022.2.1
datascience                   0.17.5
db-dtypes                     1.0.5
debugpy                       1.0.0
decorator                     4.4.2
defusedxml                    0.7.1
descartes                     1.1.0
dill                          0.3.6
distributed                   2022.2.1
dlib                          19.24.0
dm-tree                       0.1.7
dnspython                     2.2.1
docutils                      0.17.1
dopamine-rl                   1.0.5
earthengine-api               0.1.335
easydict                      1.10
ecos                          2.0.10
editdistance                  0.5.3
en-core-web-sm                3.4.1
entrypoints                   0.4
ephem                         4.1.3
et-xmlfile                    1.1.0
etils                         0.9.0
etuples                       0.3.8
fa2                           0.3.5
fastai                        2.7.10
fastcore                      1.5.27
fastdownload                  0.0.7
fastdtw                       0.3.4
fastjsonschema                2.16.2
fastprogress                  1.0.3
fastrlock                     0.8.1
feather-format                0.4.1
filelock                      3.8.2
firebase-admin                5.3.0
fix-yahoo-finance             0.0.22
Flask                         1.1.4
flatbuffers                   1.12
folium                        0.12.1.post1
frozenlist                    1.3.3
fsspec                        2022.11.0
future                        0.16.0
gast                          0.4.0
GDAL                          2.2.2
gdown                         4.4.0
gensim                        3.6.0
geographiclib                 1.52
geopy                         1.17.0
gin-config                    0.5.0
glob2                         0.7
google                        2.0.3
google-api-core               2.8.2
google-api-python-client      1.12.11
google-auth                   2.15.0
google-auth-httplib2          0.0.4
google-auth-oauthlib          0.4.6
google-cloud-bigquery         3.3.6
google-cloud-bigquery-storage 2.16.2
google-cloud-core             2.3.2
google-cloud-datastore        2.9.0
google-cloud-firestore        2.7.2
google-cloud-language         2.6.1
google-cloud-storage          2.5.0
google-cloud-translate        3.8.4
google-colab                  1.0.0
google-crc32c                 1.5.0
google-pasta                  0.2.0
google-resumable-media        2.4.0
googleapis-common-protos      1.57.0
googledrivedownloader         0.4
graphviz                      0.10.1
greenlet                      2.0.1
grpcio                        1.51.1
grpcio-status                 1.48.2
gspread                       3.4.2
gspread-dataframe             3.0.8
gym                           0.25.2
gym-notices                   0.0.8
h5py                          3.1.0
HeapDict                      1.0.1
hijri-converter               2.2.4
holidays                      0.17.2
holoviews                     1.14.9
html5lib                      1.0.1
httpimport                    0.5.18
httplib2                      0.17.4
httpstan                      4.6.1
humanize                      0.5.1
hyperopt                      0.1.2
idna                          2.10
imageio                       2.9.0
imagesize                     1.4.1
imbalanced-learn              0.8.1
imblearn                      0.0
imgaug                        0.4.0
importlib-metadata            5.1.0
importlib-resources           5.10.1
imutils                       0.5.4
inflect                       2.1.0
intel-openmp                  2022.2.1
intervaltree                  2.1.0
ipykernel                     5.3.4
ipython                       7.9.0
ipython-genutils              0.2.0
ipython-sql                   0.3.9
ipywidgets                    7.7.1
itsdangerous                  1.1.0
jax                           0.3.25
jaxlib                        0.3.25+cuda11.cudnn805
jieba                         0.42.1
Jinja2                        2.11.3
joblib                        1.2.0
jpeg4py                       0.1.4
jsonschema                    4.3.3
jupyter-client                6.1.12
jupyter-console               6.1.0
jupyter-core                  5.1.0
jupyterlab-widgets            3.0.4
kaggle                        1.5.12
kapre                         0.3.7
keras                         2.9.0
Keras-Preprocessing           1.1.2
keras-vis                     0.4.1
kiwisolver                    1.4.4
korean-lunar-calendar         0.3.1
langcodes                     3.3.0
libclang                      14.0.6
librosa                       0.8.1
lightgbm                      2.2.3
llvmlite                      0.39.1
lmdb                          0.99
locket                        1.0.0
logical-unification           0.4.5
LunarCalendar                 0.0.9
lxml                          4.9.2
Markdown                      3.4.1
MarkupSafe                    2.0.1
marshmallow                   3.19.0
matplotlib                    3.2.2
matplotlib-venn               0.11.7
miniKanren                    1.0.3
missingno                     0.5.1
mistune                       0.8.4
mizani                        0.7.3
mkl                           2019.0
mlxtend                       0.14.0
more-itertools                9.0.0
moviepy                       0.2.3.5
mpmath                        1.2.1
msgpack                       1.0.4
multidict                     6.0.3
multipledispatch              0.6.0
multitasking                  0.0.11
murmurhash                    1.0.9
music21                       5.5.0
natsort                       5.5.0
nbconvert                     5.6.1
nbformat                      5.7.0
netCDF4                       1.6.2
networkx                      2.8.8
nibabel                       3.0.2
nltk                          3.7
notebook                      5.7.16
numba                         0.56.4
numexpr                       2.8.4
numpy                         1.21.6
oauth2client                  4.1.3
oauthlib                      3.2.2
okgrade                       0.4.3
opencv-contrib-python         4.6.0.66
opencv-python                 4.6.0.66
opencv-python-headless        4.6.0.66
openpyxl                      3.0.10
opt-einsum                    3.3.0
osqp                          0.6.2.post0
packaging                     21.3
palettable                    3.3.0
pandas                        1.3.5
pandas-datareader             0.9.0
pandas-gbq                    0.17.9
pandas-profiling              1.4.1
pandocfilters                 1.5.0
panel                         0.12.1
param                         1.12.3
parso                         0.8.3
partd                         1.3.0
pastel                        0.2.1
pathlib                       1.0.1
pathy                         0.10.1
patsy                         0.5.3
pep517                        0.13.0
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        7.1.2
pip                           21.1.3
pip-tools                     6.2.0
platformdirs                  2.6.0
plotly                        5.5.0
plotnine                      0.8.0
pluggy                        0.7.1
pooch                         1.6.0
portpicker                    1.3.9
prefetch-generator            1.0.3
preshed                       3.0.8
prettytable                   3.5.0
progressbar2                  3.38.0
prometheus-client             0.15.0
promise                       2.3
prompt-toolkit                2.0.10
prophet                       1.1.1
proto-plus                    1.22.1
protobuf                      3.19.6
psutil                        5.4.8
psycopg2                      2.9.5
ptyprocess                    0.7.0
py                            1.11.0
pyarrow                       9.0.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycocotools                   2.0.6
pycparser                     2.21
pyct                          0.4.8
pydantic                      1.10.2
pydata-google-auth            1.4.0
pydot                         1.3.0
pydot-ng                      2.0.0
pydotplus                     2.0.2
PyDrive                       1.3.1
pyemd                         0.5.1
pyerfa                        2.0.0.1
Pygments                      2.6.1
pygobject                     3.26.1
pylev                         1.4.0
pymc                          4.1.4
PyMeeus                       0.5.12
pymongo                       4.3.3
pymystem3                     0.2.0
PyOpenGL                      3.1.6
pyparsing                     3.0.9
pyrsistent                    0.19.2
pysimdjson                    3.2.0
pysndfile                     1.3.8
PySocks                       1.7.1
pystan                        3.3.0
pytest                        3.6.4
python-apt                    0.0.0
python-dateutil               2.8.2
python-louvain                0.16
python-slugify                7.0.0
python-utils                  3.4.5
pytz                          2022.6
pyviz-comms                   2.2.1
PyWavelets                    1.4.1
PyYAML                        6.0
pyzmq                         23.2.1
qdldl                         0.1.5.post2
qudida                        0.0.4
regex                         2022.6.2
requests                      2.23.0
requests-oauthlib             1.3.1
resampy                       0.4.2
rpy2                          3.5.5
rsa                           4.9
scikit-image                  0.18.3
scikit-learn                  1.0.2
scipy                         1.7.3
screen-resolution-extra       0.0.0
scs                           3.2.2
seaborn                       0.11.2
Send2Trash                    1.8.0
setuptools                    57.4.0
setuptools-git                1.2
shapely                       2.0.0
six                           1.15.0
sklearn-pandas                1.8.0
smart-open                    6.3.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soundfile                     0.11.0
spacy                         3.4.4
spacy-legacy                  3.0.10
spacy-loggers                 1.0.4
Sphinx                        1.8.6
sphinxcontrib-serializinghtml 1.1.5
sphinxcontrib-websupport      1.2.4
SQLAlchemy                    1.4.45
sqlparse                      0.4.3
srsly                         2.4.5
statsmodels                   0.12.2
sympy                         1.7.1
tables                        3.7.0
tabulate                      0.8.10
tblib                         1.7.0
tenacity                      8.1.0
tensorboard                   2.9.1
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.1
tensorflow                    2.9.2
tensorflow-datasets           4.6.0
tensorflow-estimator          2.9.0
tensorflow-gcs-config         2.9.1
tensorflow-hub                0.12.0
tensorflow-io-gcs-filesystem  0.28.0
tensorflow-metadata           1.12.0
tensorflow-probability        0.17.0
termcolor                     2.1.1
terminado                     0.13.3
testpath                      0.6.0
text-unidecode                1.3
textblob                      0.15.3
thinc                         8.1.5
threadpoolctl                 3.1.0
tifffile                      2022.10.10
toml                          0.10.2
tomli                         2.0.1
toolz                         0.12.0
torch                         1.13.0+cu116
torchaudio                    0.13.0+cu116
torchsummary                  1.5.1
torchtext                     0.14.0
torchvision                   0.14.0+cu116
tornado                       6.0.4
tqdm                          4.64.1
traitlets                     5.7.1
tweepy                        3.10.0
typeguard                     2.7.1
typer                         0.7.0
typing-extensions             4.4.0
tzlocal                       1.5.1
uritemplate                   3.0.1
urllib3                       1.24.3
vega-datasets                 0.9.0
wasabi                        0.10.1
wcwidth                       0.2.5
webargs                       8.2.0
webencodings                  0.5.1
Werkzeug                      1.0.1
wheel                         0.38.4
widgetsnbextension            3.6.1
wordcloud                     1.8.2.2
wrapt                         1.14.1
xarray                        2022.12.0
xarray-einstats               0.4.0
xgboost                       0.90
xkit                          0.0.0
xlrd                          1.2.0
xlwt                          1.3.0
yarl                          1.8.2
yellowbrick                   1.5
zict                          2.2.0
zipp                          3.11.0

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

    numpy adalah modul yang memungkinkan Anda menangani array multidimensi dan melakukan operasi matematis kompleks.
    matplotlib.pyplot adalah modul yang memungkinkan Anda membuat grafik dan plot data.
    pandas adalah modul yang memungkinkan Anda memanipulasi dan menganalisis data tabel dan time series.

In [5]:
df_data = pd.read_csv('Train.csv')

 'df_data' akan menyimpan objek DataFrame yang berisi data dari file CSV bernama 'Train.csv'

In [6]:
df_data = df_data.rename(columns ={'Var_1': 'Category'})
df_data.head()

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Category,Segmentation
0,462809,Male,No,22,No,Healthcare,1.0,Low,4.0,Cat_4,D
1,462643,Female,Yes,38,Yes,Engineer,NaN,Average,3.0,Cat_4,A
2,466315,Female,Yes,67,Yes,Engineer,1.0,Low,1.0,Cat_6,B
3,461735,Male,Yes,67,Yes,Lawyer,0.0,High,2.0,Cat_6,B
4,462669,Female,Yes,40,Yes,Entertainment,NaN,High,6.0,Cat_6,A

Mengubah nama kolom 'Var_1' menjadi 'Category' pada objek df_data kemudian menampilkan baris-baris pertama dari objek df_data yang sudah diubah nama kolomnya.

In [7]:
df_data = df_data.drop(columns=['ID'])
df_data.sample(10)

,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Category,Segmentation
1439,Female,No,28,Yes,Artist,NaN,Low,2.0,Cat_6,A
7022,Female,Yes,61,Yes,Engineer,1.0,Average,5.0,Cat_6,B
2480,Male,No,27,Yes,Healthcare,NaN,Low,1.0,Cat_6,D
5862,Female,No,31,No,Doctor,1.0,Low,2.0,Cat_6,A
844,Male,No,37,Yes,Healthcare,8.0,Low,3.0,Cat_6,D
1276,Female,No,25,No,Artist,1.0,Low,3.0,Cat_6,D
568,Male,No,58,No,Healthcare,4.0,Low,2.0,Cat_6,D
3535,Male,No,23,No,Entertainment,1.0,Low,3.0,Cat_4,D
3351,Female,No,57,Yes,Doctor,0.0,Low,2.0,Cat_6,B
2551,Male,Yes,56,Yes,Executive,8.0,High,5.0,Cat_6,C

menghapus kolom 'ID' dari objek DataFrame dan menampilkan 10 baris secara acak dari objek DataFrame yang sudah dihapus kolomnya.

In [8]:
df_data.isna().sum()

Gender               0
Ever_Married       140
Age                  0
Graduated           78
Profession         124
Work_Experience    829
Spending_Score       0
Family_Size        335
Category            76
Segmentation         0
dtype: int64

 df_data.isna().sum() akan mengembalikan objek Series yang berisi jumlah elemen NaN pada setiap kolom dari objek df_data. Fungsi ini berguna untuk mengecek apakah terdapat data yang hilang atau tidak valid pada objek DataFrame, dan mengetahui jumlah data yang hilang pada setiap kolom.

In [9]:
df_data.dropna().sum()
df_data = df_data.dropna()
df_data.sample(10)

,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Category,Segmentation
1168,Male,Yes,63,No,Artist,5.0,Average,2.0,Cat_6,C
7857,Male,Yes,52,Yes,Entertainment,1.0,Average,5.0,Cat_6,C
8015,Male,Yes,37,Yes,Entertainment,1.0,Low,2.0,Cat_3,A
1137,Male,Yes,72,Yes,Entertainment,7.0,Low,2.0,Cat_6,A
5782,Male,Yes,43,Yes,Engineer,0.0,Average,2.0,Cat_6,B
1826,Male,Yes,50,Yes,Artist,1.0,Average,4.0,Cat_6,C
2443,Female,Yes,56,Yes,Artist,0.0,Average,2.0,Cat_6,C
1289,Male,Yes,37,Yes,Executive,9.0,High,4.0,Cat_6,C
121,Male,Yes,55,No,Executive,1.0,High,4.0,Cat_3,B
4113,Male,Yes,41,Yes,Artist,0.0,High,3.0,Cat_6,C

menghapus baris yang mengandung elemen NaN dari objek df_data, kemudian mengembalikan 10 baris secara acak dari objek df_data yang sudah dihapus barisnya.

# Covert non-numerical values into numerical values

In [10]:
def get_encoded_dict(values):
    return {val:i for i, val in enumerate(values)}

 get_encoded_dict() adalah sebuah fungsi menerima satu parameter bernama values, yang merupakan sebuah list yang akan di-encode menjadi sebuah dictionary. kemudian mengembalikan sebuah dictionary yang dihasilkan dengan menggunakan expression dictionary. Expression dictionary adalah cara sintaks Python untuk menuliskan sebuah dictionary dengan menggunakan syntax `{key:value for item in iterable}`.

In [11]:
gender_dict = get_encoded_dict(df_data.Gender.unique())
married_dict = get_encoded_dict(df_data.Ever_Married.unique())
grad_dict = get_encoded_dict(df_data.Graduated.unique())
Profession_dict = get_encoded_dict(df_data.Profession.unique())
spend_dict = get_encoded_dict(df_data.Spending_Score.unique())
cat_dict = get_encoded_dict(df_data.Category.unique())
segment_dict = get_encoded_dict(df_data.Segmentation.unique())
segment_dict

{'D': 0, 'B': 1, 'C': 2, 'A': 3}

kode tersebut membuat beberapa dictionary yang masing-masing menyimpan encoding untuk setiap unique value dari kolom-kolom tertentu dari objek DataFrame df_data.

Untuk membuat dictionary tersebut, kode tersebut memanggil fungsi get_encoded_dict() dengan menggunakan unique values dari masing-masing kolom sebagai parameter. Fungsi get_encoded_dict() kemudian akan mengembalikan dictionary yang meng-encode setiap elemen dari parameter tersebut menjadi integer dengan menggunakan indeks dari setiap elemen sebagai value dari entry dalam dictionary.

In [12]:
encoded_dict = {
    'Gender' : gender_dict,
    'Ever_Married': married_dict,
    'Graduated' : grad_dict,
    'Profession': Profession_dict,
    'Spending_Score': spend_dict,
     'Category': cat_dict,
    'Segmentation': segment_dict
}

kode tersebut digunakan untuk membuat sebuah dictionary yang menyimpan encoding untuk setiap unique value dari beberapa kolom dari objek DataFrame df_data.

In [13]:
df_data = df_data.replace(encoded_dict)
df_data.sample(10)

,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Category,Segmentation
1836,0,0,20,0,7,0.0,0,2.0,1,0
570,1,0,31,1,3,1.0,0,4.0,1,0
7330,1,0,31,0,5,8.0,0,1.0,1,0
7212,0,1,55,1,3,9.0,2,2.0,4,2
1858,0,1,36,0,1,0.0,0,1.0,1,0
4724,1,0,32,1,1,9.0,0,1.0,1,3
1704,0,1,47,0,6,1.0,2,5.0,1,2
7667,0,1,71,0,8,0.0,1,4.0,1,2
61,0,1,55,1,3,9.0,2,2.0,4,2
8055,0,0,18,0,0,0.0,0,2.0,1,0

kode tersebut akan mengubah elemen-elemen dari objek df_data yang cocok dengan key dari encoded_dict menjadi value dari key tersebut

In [14]:
df_data.columns

Index(['Gender', 'Ever_Married', 'Age', 'Graduated', 'Profession',
       'Work_Experience', 'Spending_Score', 'Family_Size', 'Category',
       'Segmentation'],
      dtype='object')

df_data.columns akan mengembalikan nama-nama kolom dari objek df_data dalam bentuk sebuah Index objek.

In [15]:
feature_cols = ['Gender', 'Ever_Married', 'Age', 'Graduated', 'Profession','Work_Experience', 'Spending_Score', 'Family_Size', 'Category']
target_col = ['Segmentation']

 feature_cols akan berisi nama-nama kolom yang akan digunakan sebagai fitur dalam suatu proses machine learning, sedangkan target_col akan berisi nama satu kolom yang akan digunakan sebagai target dalam proses tersebut.

In [16]:
from sklearn.model_selection import train_test_split
data_x = df_data.loc[:, feature_cols]
data_y = df_data.loc[:, target_col]
train_x,test_x,train_y,test_y = train_test_split(data_x, data_y, test_size=0.2)

Fungsi train_test_split() adalah fungsi yang digunakan untuk membagi data menjadi data training dan data testing. Fungsi ini menerima empat parameter yaitu data_x, data_y, test_size, dan random_state.

    data_x adalah fitur dari data yang akan dibagi.
    data_y adalah target dari data yang akan dibagi.
    test_size adalah proporsi dari data yang akan dimasukkan ke dalam data testing. Nilai test_size harus berada di antara 0 dan 1.
    random_state adalah seed yang digunakan oleh fungsi untuk menentukan urutan acak dari data.

In [17]:
print(train_x.shape)
print(train_y.shape)
print(test_x.shape)
print(test_y.shape)

(5332, 9)
(5332, 1)
(1333, 9)
(1333, 1)

menampilkan tran_x,y dan test_x,y

In [18]:
from sklearn.naive_bayes import CategoricalNB
cnb = CategoricalNB()
cnb.fit(train_x.to_numpy(), train_y.to_numpy().reshape(-1))

CategoricalNB()

In [19]:
actual_y = test_y.to_numpy().reshape(-1)
predicted_y = cnb.predict(test_x.to_numpy())

 actual_y diinisialisasi dengan mengubah objek DataFrame test_y menjadi array numpy dengan menggunakan method to_numpy(), kemudian mengubah bentuk array tersebut dengan menggunakan method reshape(-1). Method reshape(-1) akan mengubah bentuk array menjadi sebuah vektor dengan panjang sesuai dengan jumlah elemen dari array tersebut.

Sedangkan predicted_y diinisialisasi dengan mengubah objek DataFrame test_x menjadi array numpy dengan menggunakan method to_numpy(), kemudian memprediksi nilai output dari model machine learning yang telah dibuat pada data testing dengan menggunakan method predict() pada objek model tersebut dan menyimpan hasil prediksi tersebut dalam variabel predicted_y.

In [20]:
actual_y

array([2, 3, 3, ..., 2, 0, 1])

In [26]:
predicted_y

array([2, 2, 1, ..., 2, 0, 3])

# Confusion matrix,Classification_Report

In [22]:
from sklearn import metrics
metrics.accuracy_score(actual_y, predicted_y)

0.5446361590397599

Jika hasil accuracy bernilai 0.54, artinya hasil prediksi dari model machine learning tersebut memiliki akurasi sebesar 54%. Hal ini berarti bahwa dari seluruh hasil prediksi yang dibuat oleh model machine learning tersebut, sebanyak 54% di antaranya sesuai dengan target dari data testing.

Nilai accuracy yang rendah menunjukkan bahwa model machine learning tersebut tidak terlalu baik dalam memprediksi target dari data testing. Hal ini bisa disebabkan karena beberapa faktor seperti kurangnya data yang tersedia, kurang baiknya fitur yang digunakan, atau model machine learning yang kurang tepat. Namun demikian, nilai accuracy tersebut masih bisa diperbaiki dengan cara menambah data yang tersedia, menggunakan fitur yang lebih baik, atau menggunakan model machine learning yang lebih tepat.

In [23]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(actual_y,predicted_y))

[[255  24  13  66]
 [ 37  80 104  85]
 [ 33  41 235  36]
 [ 45  60  63 156]]

In [24]:
segment_dict

{'D': 0, 'B': 1, 'C': 2, 'A': 3}

In [25]:
print(classification_report(actual_y, predicted_y, target_names=['D','B','C','A']))

              precision    recall  f1-score   support

           D       0.69      0.71      0.70       358
           B       0.39      0.26      0.31       306
           C       0.57      0.68      0.62       345
           A       0.45      0.48      0.47       324

    accuracy                           0.54      1333
   macro avg       0.53      0.53      0.52      1333
weighted avg       0.53      0.54      0.53      1333